package com.bosco.stdata.teaModel;

import lombok.Data;

@Data
public class AllenStudent {
    public String studentID;
    public String teacherID;
    public String lastName;
    public String firstName;
    public String studentEmail;
    public String studentPhoneNumber;
    public String dOB;
    public String gender;
    public String isHispanicLatino;
    public String americanIndianOrAlaskaNative;
    public String asian;
    public String blackOrAfricanAmerican;
    public String nativeHawaiianOtherPacificIslander;
    public String white;
    public String isEsl;
    public String isBilingual;
    public String isSpecialEd;
    public String is504;
    public String iEPDate;
    public String homeless;
    public String fosterCare;
    public String englishLanguageLearner;
    public String mealStatus;
    public String schoolCode;
    public String gradeCode;
    public String orthopedicImpairment;
    public String otherHealthImpaired;
    public String hearingImpairment;
    public String visualImpairment;
    public String deafness;
    public String deafBlind;
    public String intellectualDisability;
    public String emotionalDisturbance;
    public String specificLearningDisabilities;
    public String speechOrLanguageImpairment;
    public String autism;
    public String multipleDisabilities;
    public String developmentalDelay;
    public String traumaticBrainInjury;
    public String noncategoricalEarlyChildhood;
    public String guardianType;
    public String guardianLastName;
    public String guardianFirstName;
    public String guardianEmail;
    public String guardianAddress1;
    public String guardianAddress2;
    public String guardianCity;
    public String guardianState;
    public String guardianZip;
    public String guardianHomePhone;
    public String guardianMobilePhone;
    public String guardianWorkPhone;
    public String guardian2Type;
    public String guardian2LastName;
    public String guardian2FirstName;
    public String guardian2Email;
    public String guardian2Address1;
    public String guardian2Address2;
    public String guardian2City;
    public String guardian2State;
    public String guardian2Zip;
    public String guardian2HomePhone;
    public String guardian2MobilePhone;
    public String guardian2WorkPhone;
    public String guardian3Type;
    public String guardian3LastName;
    public String guardian3FirstName;
    public String guardian3Email;
    public String guardian3Address1;
    public String guardian3Address2;
    public String guardian3City;
    public String guardian3State;
    public String guardian3Zip;
    public String guardian3HomePhone;
    public String guardian3MobilePhone;
    public String guardian3WorkPhone;

}
